### ISSUE TITLE
clean: rename `shared::wrapper::Wrapper` field wrap to event.

### ISSUE THREAD

**Issue by 0xB10C** [0xB10C/peer-observer#18]
Currently, the `shared::wrapper::Wrapper` field `wrap` isn't really expressive of what it is. It's a peer-observer `event` and should be renamed.

![image](https://github.com/0xB10C/peer-observer/assets/19157360/791a166b-378d-40ae-8828-ba665e35ec59)

**Comment by 0xB10C** [comment]
Same goes for `shared::wrapper::wrapper::Wrap`

**Comment by i-am-yuvi** [comment]
Can I give it a try??

**Comment by 0xB10C** [comment]
Sure, no need to ask!

**Comment by i-am-yuvi** [comment]
@0xB10C I basically need to replace the Wrap field inside the struct to event right??

**Comment by i-am-yuvi** [comment]
Yes, it is already commented that structs are generated from the protobuf definitions.

**Comment by i-am-yuvi** [comment]
I think we can also update the rename it to event.proto ?? @0xB10C

**Comment by 0xB10C** [comment]
agree

**Comment by i-am-yuvi** [comment]
I have updated everything from wrap -> event & Wrapper -> Event. Is that fine??

**Comment by 0xB10C** [comment]
Feel free to open a PR and I'll have a look there

**Comment by 0xB10C** [comment]
Closed with #25
