### ISSUE TITLE
depends: update rust-bitcoin

### ISSUE THREAD

**Issue by 0xB10C** [0xB10C/peer-observer#20]
Currently, rust bitcoin v0.29.2 is used. Current latest release is https://github.com/rust-bitcoin/rust-bitcoin/releases/tag/bitcoin-0.30.2

**Comment by i-am-yuvi** [comment]
I'll try this 🙌

**Comment by 0xB10C** [comment]
Note that rust-bitcoin 30.2 is the latest release on GitHub, but not the latest version of the crate on https://crates.io/crates/bitcoin. We should update to the latest version of the crate if possible.

**Comment by i-am-yuvi** [comment]
yes even I was thinking the same, in [docs.rs/bitcoin](https://docs.rs/bitcoin/) it shows 0.32.2

**Comment by 0xB10C** [comment]
I've opened a PR in https://github.com/0xB10C/peer-observer/issues/31 for this. I wasn't sure if you were still working on it.

**Comment by i-am-yuvi** [comment]
> I've opened a PR in #31 for this. I wasn't sure if you were still working on it.

okay, I was working on it!! but no worries!!
